-- MySQL Script generated by MySQL Workbench
-- Tue Aug 25 18:26:53 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`tipoUsuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`tipoUsuario` ;

CREATE TABLE IF NOT EXISTS `mydb`.`tipoUsuario` (
  `idTipoUsuario` INT NOT NULL,
  `nivelAcceso` INT NOT NULL,
  `descripcion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idTipoUsuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`inventario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`inventario` ;

CREATE TABLE IF NOT EXISTS `mydb`.`inventario` (
  `id_inventario` INT NOT NULL,
  `nombre_empresa` VARCHAR(45) NOT NULL,
  `total_productos` VARCHAR(45) NOT NULL,
  `Usuario_idUsuarios` INT NOT NULL,
  `Usuario_tipoUsuario_idTipoUsuario` INT NOT NULL,
  PRIMARY KEY (`id_inventario`, `Usuario_idUsuarios`, `Usuario_tipoUsuario_idTipoUsuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Usuario` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Usuario` (
  `idUsuarios` INT NOT NULL,
  `nombreUsuario` VARCHAR(45) NOT NULL,
  `apellidoUsuario` VARCHAR(45) NOT NULL,
  `emailUsuario` VARCHAR(45) NOT NULL,
  `contraseñaUsuario` VARCHAR(45) NOT NULL,
  `tienda` VARCHAR(45) NOT NULL,
  `creacion_usuario` DATE NULL,
  `fecha_login` VARCHAR(45) NULL,
  `turnos_laborales` VARCHAR(45) NULL,
  `cedula_ciudadania` BIGINT NULL,
  `tipoUsuario_idTipoUsuario` INT NOT NULL,
  `participación_evento` INT NULL,
  `tipoUsuario_idTipoUsuario1` INT NOT NULL,
  `inventario_id_inventario` INT NOT NULL,
  `inventario_Usuario_idUsuarios` INT NOT NULL,
  `inventario_Usuario_tipoUsuario_idTipoUsuario` INT NOT NULL,
  PRIMARY KEY (`idUsuarios`, `tipoUsuario_idTipoUsuario`, `tipoUsuario_idTipoUsuario1`, `inventario_id_inventario`, `inventario_Usuario_idUsuarios`, `inventario_Usuario_tipoUsuario_idTipoUsuario`),
  INDEX `fk_Usuario_tipoUsuario1_idx` (`tipoUsuario_idTipoUsuario1` ASC) VISIBLE,
  INDEX `fk_Usuario_inventario1_idx` (`inventario_id_inventario` ASC, `inventario_Usuario_idUsuarios` ASC, `inventario_Usuario_tipoUsuario_idTipoUsuario` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`detallePedido`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`detallePedido` ;

CREATE TABLE IF NOT EXISTS `mydb`.`detallePedido` (
  `iddetallePedido` INT NOT NULL,
  `valorApagar` BIGINT NULL,
  `producto` VARCHAR(45) NULL,
  `cantidadProducto` INT NULL,
  PRIMARY KEY (`iddetallePedido`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pedidos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`pedidos` ;

CREATE TABLE IF NOT EXISTS `mydb`.`pedidos` (
  `idPedidos` INT NOT NULL,
  `estadoPedido` VARCHAR(45) NOT NULL,
  `mesa` INT NOT NULL,
  `numeroPedido` BIGINT NOT NULL,
  `detallePedido_iddetallePedido` INT NOT NULL,
  `Usuario_idUsuarios` INT NOT NULL,
  `Usuario_tipoUsuario_idTipoUsuario` INT NOT NULL,
  `Usuario_tipoUsuario_idTipoUsuario1` INT NOT NULL,
  `Usuario_inventario_id_inventario` INT NOT NULL,
  `Usuario_inventario_Usuario_idUsuarios` INT NOT NULL,
  `Usuario_inventario_Usuario_tipoUsuario_idTipoUsuario` INT NOT NULL,
  PRIMARY KEY (`idPedidos`, `detallePedido_iddetallePedido`, `Usuario_idUsuarios`, `Usuario_tipoUsuario_idTipoUsuario`, `Usuario_tipoUsuario_idTipoUsuario1`, `Usuario_inventario_id_inventario`, `Usuario_inventario_Usuario_idUsuarios`, `Usuario_inventario_Usuario_tipoUsuario_idTipoUsuario`),
  INDEX `fk_Estado_pedidos_detallePedido1_idx` (`detallePedido_iddetallePedido` ASC) VISIBLE,
  INDEX `fk_pedidos_Usuario1_idx` (`Usuario_idUsuarios` ASC, `Usuario_tipoUsuario_idTipoUsuario` ASC, `Usuario_tipoUsuario_idTipoUsuario1` ASC, `Usuario_inventario_id_inventario` ASC, `Usuario_inventario_Usuario_idUsuarios` ASC, `Usuario_inventario_Usuario_tipoUsuario_idTipoUsuario` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pedidos_has_Pedidos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Pedidos_has_Pedidos` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Pedidos_has_Pedidos` (
  `Pedidos_idUsuarios` INT NOT NULL,
  `Pedidos_tipoUsuario_idTipoUsuario` INT NOT NULL,
  `Pedidos_idPedidos` INT NOT NULL,
  PRIMARY KEY (`Pedidos_idUsuarios`, `Pedidos_tipoUsuario_idTipoUsuario`, `Pedidos_idPedidos`),
  INDEX `fk_Pedidos_has_Pedidos_Pedidos2_idx` (`Pedidos_idPedidos` ASC) VISIBLE,
  INDEX `fk_Pedidos_has_Pedidos_Pedidos1_idx` (`Pedidos_idUsuarios` ASC, `Pedidos_tipoUsuario_idTipoUsuario` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`estado_pedido`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`estado_pedido` ;

CREATE TABLE IF NOT EXISTS `mydb`.`estado_pedido` (
  `id_Estado_pedido` INT NOT NULL,
  `State_id` INT NULL,
  `descripcion` VARCHAR(45) NULL,
  `Estado_pedidos_idPedidos` INT NOT NULL,
  `Estado_pedidos_detallePedido_iddetallePedido` INT NOT NULL,
  PRIMARY KEY (`id_Estado_pedido`, `Estado_pedidos_idPedidos`, `Estado_pedidos_detallePedido_iddetallePedido`),
  INDEX `fk_Estado_pedido_Estado_pedidos1_idx` (`Estado_pedidos_idPedidos` ASC, `Estado_pedidos_detallePedido_iddetallePedido` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`detalle_evento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`detalle_evento` ;

CREATE TABLE IF NOT EXISTS `mydb`.`detalle_evento` (
  `id_detalle_evento` INT NOT NULL,
  `tipo_evento` VARCHAR(45) NOT NULL,
  `servicio_ofrecido` VARCHAR(45) NOT NULL,
  `imagen_evento` VARCHAR(45) NULL,
  PRIMARY KEY (`id_detalle_evento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Eventos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Eventos` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Eventos` (
  `idEventos` INT NOT NULL,
  `nombre_evento` VARCHAR(45) NOT NULL,
  `autor_evento` VARCHAR(45) NOT NULL,
  `Usuario_idUsuarios` INT NOT NULL,
  `Usuario_tipoUsuario_idTipoUsuario` INT NOT NULL,
  `detalle_evento_id_detalle_evento` INT NOT NULL,
  PRIMARY KEY (`idEventos`, `Usuario_idUsuarios`, `Usuario_tipoUsuario_idTipoUsuario`, `detalle_evento_id_detalle_evento`),
  INDEX `fk_Eventos_Usuario1_idx` (`Usuario_idUsuarios` ASC, `Usuario_tipoUsuario_idTipoUsuario` ASC) VISIBLE,
  INDEX `fk_Eventos_detalle_evento1_idx` (`detalle_evento_id_detalle_evento` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cancion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`cancion` ;

CREATE TABLE IF NOT EXISTS `mydb`.`cancion` (
  `id_cancion` INT NOT NULL,
  `nombre_cancion` VARCHAR(45) NULL,
  `autor` VARCHAR(45) NULL,
  `duracion` VARCHAR(45) NULL,
  PRIMARY KEY (`id_cancion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`genero`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`genero` ;

CREATE TABLE IF NOT EXISTS `mydb`.`genero` (
  `id_genero` INT NOT NULL,
  `descripción` VARCHAR(45) NULL,
  PRIMARY KEY (`id_genero`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`album_musical`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`album_musical` ;

CREATE TABLE IF NOT EXISTS `mydb`.`album_musical` (
  `id_album_musical` INT NOT NULL,
  `nombre_album` VARCHAR(45) NULL,
  `autor_album` VARCHAR(45) NULL,
  `cancion_id_cancion` INT NOT NULL,
  `Usuario_idUsuarios` INT NOT NULL,
  `Usuario_tipoUsuario_idTipoUsuario` INT NOT NULL,
  `genero_id_genero` INT NOT NULL,
  PRIMARY KEY (`id_album_musical`, `cancion_id_cancion`, `Usuario_idUsuarios`, `Usuario_tipoUsuario_idTipoUsuario`, `genero_id_genero`),
  INDEX `fk_album_musical_cancion1_idx` (`cancion_id_cancion` ASC) VISIBLE,
  INDEX `fk_album_musical_Usuario1_idx` (`Usuario_idUsuarios` ASC, `Usuario_tipoUsuario_idTipoUsuario` ASC) VISIBLE,
  INDEX `fk_album_musical_genero1_idx` (`genero_id_genero` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`categoria_producto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`categoria_producto` ;

CREATE TABLE IF NOT EXISTS `mydb`.`categoria_producto` (
  `id_categoria_producto` INT NOT NULL,
  `tipo_categoria` VARCHAR(45) NULL,
  PRIMARY KEY (`id_categoria_producto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`productos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`productos` ;

CREATE TABLE IF NOT EXISTS `mydb`.`productos` (
  `id_productos` INT NOT NULL,
  `nombre_producto` VARCHAR(45) NULL,
  `codigo_producto` VARCHAR(45) NULL,
  `estado_producto` VARCHAR(45) NULL,
  `cantidad_producto` INT NULL,
  `fecha_ingreso` DATE NULL,
  `productoscol` VARCHAR(45) NULL,
  `inventario_id_inventario` INT NOT NULL,
  `inventario_Usuario_idUsuarios` INT NOT NULL,
  `inventario_Usuario_tipoUsuario_idTipoUsuario` INT NOT NULL,
  `categoria_producto_id_categoria_producto` INT NOT NULL,
  PRIMARY KEY (`id_productos`, `inventario_id_inventario`, `inventario_Usuario_idUsuarios`, `inventario_Usuario_tipoUsuario_idTipoUsuario`, `categoria_producto_id_categoria_producto`),
  INDEX `fk_productos_inventario1_idx` (`inventario_id_inventario` ASC, `inventario_Usuario_idUsuarios` ASC, `inventario_Usuario_tipoUsuario_idTipoUsuario` ASC) VISIBLE,
  INDEX `fk_productos_categoria_producto1_idx` (`categoria_producto_id_categoria_producto` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`detalle_productos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`detalle_productos` ;

CREATE TABLE IF NOT EXISTS `mydb`.`detalle_productos` (
  `id_detalle_productos` INT NOT NULL,
  `valor_inicial` VARCHAR(45) NULL,
  `valor_mas_iva` VARCHAR(45) NULL,
  `descripcion_producto` VARCHAR(45) NULL,
  `productos_id_productos` INT NOT NULL,
  `productos_inventario_id_inventario` INT NOT NULL,
  `productos_inventario_Usuario_idUsuarios` INT NOT NULL,
  `productos_inventario_Usuario_tipoUsuario_idTipoUsuario` INT NOT NULL,
  PRIMARY KEY (`id_detalle_productos`, `productos_id_productos`, `productos_inventario_id_inventario`, `productos_inventario_Usuario_idUsuarios`, `productos_inventario_Usuario_tipoUsuario_idTipoUsuario`),
  INDEX `fk_detalle_productos_productos1_idx` (`productos_id_productos` ASC, `productos_inventario_id_inventario` ASC, `productos_inventario_Usuario_idUsuarios` ASC, `productos_inventario_Usuario_tipoUsuario_idTipoUsuario` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`proveedor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`proveedor` ;

CREATE TABLE IF NOT EXISTS `mydb`.`proveedor` (
  `id_proveedor` INT NOT NULL,
  `contacto` VARCHAR(45) NULL,
  `nombre_proveedor` VARCHAR(45) NULL,
  PRIMARY KEY (`id_proveedor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`proveedor_has_productos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`proveedor_has_productos` ;

CREATE TABLE IF NOT EXISTS `mydb`.`proveedor_has_productos` (
  `proveedor_id_proveedor` INT NOT NULL,
  `productos_id_productos` INT NOT NULL,
  `productos_inventario_id_inventario` INT NOT NULL,
  `productos_inventario_Usuario_idUsuarios` INT NOT NULL,
  `productos_inventario_Usuario_tipoUsuario_idTipoUsuario` INT NOT NULL,
  PRIMARY KEY (`proveedor_id_proveedor`, `productos_id_productos`, `productos_inventario_id_inventario`, `productos_inventario_Usuario_idUsuarios`, `productos_inventario_Usuario_tipoUsuario_idTipoUsuario`),
  INDEX `fk_proveedor_has_productos_productos1_idx` (`productos_id_productos` ASC, `productos_inventario_id_inventario` ASC, `productos_inventario_Usuario_idUsuarios` ASC, `productos_inventario_Usuario_tipoUsuario_idTipoUsuario` ASC) VISIBLE,
  INDEX `fk_proveedor_has_productos_proveedor1_idx` (`proveedor_id_proveedor` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`usuarioEvento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`usuarioEvento` ;

CREATE TABLE IF NOT EXISTS `mydb`.`usuarioEvento` (
  `id_usuario_Evento` INT NOT NULL AUTO_INCREMENT,
  `nombre_usuario_participacion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_usuario_Evento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Usuario_has_usuarioEvento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Usuario_has_usuarioEvento` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Usuario_has_usuarioEvento` (
  `Usuario_idUsuarios` INT NOT NULL,
  `Usuario_tipoUsuario_idTipoUsuario` INT NOT NULL,
  `Usuario_tipoUsuario_idTipoUsuario1` INT NOT NULL,
  `Usuario_inventario_id_inventario` INT NOT NULL,
  `Usuario_inventario_Usuario_idUsuarios` INT NOT NULL,
  `Usuario_inventario_Usuario_tipoUsuario_idTipoUsuario` INT NOT NULL,
  `usuarioEvento_idusuarioEvento` INT NOT NULL,
  PRIMARY KEY (`Usuario_idUsuarios`, `Usuario_tipoUsuario_idTipoUsuario`, `Usuario_tipoUsuario_idTipoUsuario1`, `Usuario_inventario_id_inventario`, `Usuario_inventario_Usuario_idUsuarios`, `Usuario_inventario_Usuario_tipoUsuario_idTipoUsuario`, `usuarioEvento_idusuarioEvento`),
  INDEX `fk_Usuario_has_usuarioEvento_usuarioEvento1_idx` (`usuarioEvento_idusuarioEvento` ASC) VISIBLE,
  INDEX `fk_Usuario_has_usuarioEvento_Usuario1_idx` (`Usuario_idUsuarios` ASC, `Usuario_tipoUsuario_idTipoUsuario` ASC, `Usuario_tipoUsuario_idTipoUsuario1` ASC, `Usuario_inventario_id_inventario` ASC, `Usuario_inventario_Usuario_idUsuarios` ASC, `Usuario_inventario_Usuario_tipoUsuario_idTipoUsuario` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`usuarioMusica`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`usuarioMusica` ;

CREATE TABLE IF NOT EXISTS `mydb`.`usuarioMusica` (
  `idusuarioMusica` INT NOT NULL AUTO_INCREMENT,
  `mesa_cancion` VARCHAR(45) NULL,
  PRIMARY KEY (`idusuarioMusica`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`usuarioMusica_has_Usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`usuarioMusica_has_Usuario` ;

CREATE TABLE IF NOT EXISTS `mydb`.`usuarioMusica_has_Usuario` (
  `usuarioMusica_idusuarioMusica` INT NOT NULL,
  `Usuario_idUsuarios` INT NOT NULL,
  `Usuario_tipoUsuario_idTipoUsuario` INT NOT NULL,
  `Usuario_tipoUsuario_idTipoUsuario1` INT NOT NULL,
  `Usuario_inventario_id_inventario` INT NOT NULL,
  `Usuario_inventario_Usuario_idUsuarios` INT NOT NULL,
  `Usuario_inventario_Usuario_tipoUsuario_idTipoUsuario` INT NOT NULL,
  PRIMARY KEY (`usuarioMusica_idusuarioMusica`, `Usuario_idUsuarios`, `Usuario_tipoUsuario_idTipoUsuario`, `Usuario_tipoUsuario_idTipoUsuario1`, `Usuario_inventario_id_inventario`, `Usuario_inventario_Usuario_idUsuarios`, `Usuario_inventario_Usuario_tipoUsuario_idTipoUsuario`),
  INDEX `fk_usuarioMusica_has_Usuario_Usuario1_idx` (`Usuario_idUsuarios` ASC, `Usuario_tipoUsuario_idTipoUsuario` ASC, `Usuario_tipoUsuario_idTipoUsuario1` ASC, `Usuario_inventario_id_inventario` ASC, `Usuario_inventario_Usuario_idUsuarios` ASC, `Usuario_inventario_Usuario_tipoUsuario_idTipoUsuario` ASC) VISIBLE,
  INDEX `fk_usuarioMusica_has_Usuario_usuarioMusica1_idx` (`usuarioMusica_idusuarioMusica` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Eventos_has_usuarioEvento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Eventos_has_usuarioEvento` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Eventos_has_usuarioEvento` (
  `Eventos_idEventos` INT NOT NULL,
  `Eventos_Usuario_idUsuarios` INT NOT NULL,
  `Eventos_Usuario_tipoUsuario_idTipoUsuario` INT NOT NULL,
  `Eventos_detalle_evento_id_detalle_evento` INT NOT NULL,
  `usuarioEvento_id_usuario_Evento` INT NOT NULL,
  PRIMARY KEY (`Eventos_idEventos`, `Eventos_Usuario_idUsuarios`, `Eventos_Usuario_tipoUsuario_idTipoUsuario`, `Eventos_detalle_evento_id_detalle_evento`, `usuarioEvento_id_usuario_Evento`),
  INDEX `fk_Eventos_has_usuarioEvento_usuarioEvento1_idx` (`usuarioEvento_id_usuario_Evento` ASC) VISIBLE,
  INDEX `fk_Eventos_has_usuarioEvento_Eventos1_idx` (`Eventos_idEventos` ASC, `Eventos_Usuario_idUsuarios` ASC, `Eventos_Usuario_tipoUsuario_idTipoUsuario` ASC, `Eventos_detalle_evento_id_detalle_evento` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cancion_has_usuarioMusica`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`cancion_has_usuarioMusica` ;

CREATE TABLE IF NOT EXISTS `mydb`.`cancion_has_usuarioMusica` (
  `cancion_id_cancion` INT NOT NULL,
  `usuarioMusica_idusuarioMusica` INT NOT NULL,
  PRIMARY KEY (`cancion_id_cancion`, `usuarioMusica_idusuarioMusica`),
  INDEX `fk_cancion_has_usuarioMusica_usuarioMusica1_idx` (`usuarioMusica_idusuarioMusica` ASC) VISIBLE,
  INDEX `fk_cancion_has_usuarioMusica_cancion1_idx` (`cancion_id_cancion` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pedidos_has_productos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`pedidos_has_productos` ;

CREATE TABLE IF NOT EXISTS `mydb`.`pedidos_has_productos` (
  `pedidos_idPedidos` INT NOT NULL,
  `pedidos_detallePedido_iddetallePedido` INT NOT NULL,
  `pedidos_Usuario_idUsuarios` INT NOT NULL,
  `pedidos_Usuario_tipoUsuario_idTipoUsuario` INT NOT NULL,
  `pedidos_Usuario_tipoUsuario_idTipoUsuario1` INT NOT NULL,
  `pedidos_Usuario_inventario_id_inventario` INT NOT NULL,
  `pedidos_Usuario_inventario_Usuario_idUsuarios` INT NOT NULL,
  `pedidos_Usuario_inventario_Usuario_tipoUsuario_idTipoUsuario` INT NOT NULL,
  `productos_id_productos` INT NOT NULL,
  `productos_inventario_id_inventario` INT NOT NULL,
  `productos_inventario_Usuario_idUsuarios` INT NOT NULL,
  `productos_inventario_Usuario_tipoUsuario_idTipoUsuario` INT NOT NULL,
  `productos_categoria_producto_id_categoria_producto` INT NOT NULL,
  PRIMARY KEY (`pedidos_idPedidos`, `pedidos_detallePedido_iddetallePedido`, `pedidos_Usuario_idUsuarios`, `pedidos_Usuario_tipoUsuario_idTipoUsuario`, `pedidos_Usuario_tipoUsuario_idTipoUsuario1`, `pedidos_Usuario_inventario_id_inventario`, `pedidos_Usuario_inventario_Usuario_idUsuarios`, `pedidos_Usuario_inventario_Usuario_tipoUsuario_idTipoUsuario`, `productos_id_productos`, `productos_inventario_id_inventario`, `productos_inventario_Usuario_idUsuarios`, `productos_inventario_Usuario_tipoUsuario_idTipoUsuario`, `productos_categoria_producto_id_categoria_producto`),
  INDEX `fk_pedidos_has_productos_productos1_idx` (`productos_id_productos` ASC, `productos_inventario_id_inventario` ASC, `productos_inventario_Usuario_idUsuarios` ASC, `productos_inventario_Usuario_tipoUsuario_idTipoUsuario` ASC, `productos_categoria_producto_id_categoria_producto` ASC) VISIBLE,
  INDEX `fk_pedidos_has_productos_pedidos1_idx` (`pedidos_idPedidos` ASC, `pedidos_detallePedido_iddetallePedido` ASC, `pedidos_Usuario_idUsuarios` ASC, `pedidos_Usuario_tipoUsuario_idTipoUsuario` ASC, `pedidos_Usuario_tipoUsuario_idTipoUsuario1` ASC, `pedidos_Usuario_inventario_id_inventario` ASC, `pedidos_Usuario_inventario_Usuario_idUsuarios` ASC, `pedidos_Usuario_inventario_Usuario_tipoUsuario_idTipoUsuario` ASC) VISIBLE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
